### ISSUE TITLE
is maxMessageLength configurable?

### ISSUE THREAD

**Issue by mingfai** [aeron-io/aeron#41]
I'm getting a `java.lang.IllegalArgumentException: encoded message exceeds maxMessageLength of 65536` error when trying to send a large message to an UDP address. Is the max message length configurable?

**Comment by GenuineJyn** [comment]
Aeron/aeron-driver/src/main/java/io/aeron/driver/Configuration.java
/**                                                                                             
     * Length (in bytes) of the log buffers for publication terms.                                  
     */                                                                                             
    public static final String TERM_BUFFER_LENGTH_PROP_NAME = "aeron.term.buffer.length";           
                                                                                                    
    /**                                                                                             
     * Default term buffer length.                                                                  
     */                                                                                             

    public static final int TERM_BUFFER_LENGTH_DEFAULT = 16 * 1024 * 1024;

You can use -Daeron.term.buffer.length=XXX to configure it.
